# Site settings
title: Jerome Isaacs
email: jerome.isaacs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "/jerome-personal" # the subpath of your site, e.g. /blog/
url: http://jboo1212.github.io" # the base hostname & protocol for your site
twitter_username: jerome_isaacs12
github_username: jboo1212

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
regeneration: -w
exclude: [_posts/2015-05-25-formatting-samples.markdown]
